name: whisptask
description: A smart voice-activated task management app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0  # Updated to latest version
  firebase_auth: ^6.0.1  # Updated to latest version
  cloud_firestore: ^6.0.0  # Updated to latest version

  # Voice Recognition
  speech_to_text: ^7.3.0  # Updated to latest version
  permission_handler: ^12.0.1  # Updated to latest version
  
  # State Management
  provider: ^6.0.5

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
