// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZsHgHdkJMSaaIvnmNa_sjaIIcxtXYZ4',
    appId: '1:402878727922:web:b4f2ac977f8977d89c726b',
    messagingSenderId: '402878727922',
    projectId: 'whisptask',
    authDomain: 'whisptask.firebaseapp.com',
    storageBucket: 'whisptask.firebasestorage.app',
    measurementId: 'G-8Y5LDGZKFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:402878727922:android:abcdefghijklmnop',
    messagingSenderId: '402878727922',
    projectId: 'whisptask',
    storageBucket: 'whisptask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:402878727922:ios:abcdefghijklmnop',
    messagingSenderId: '402878727922',
    projectId: 'whisptask',
    storageBucket: 'whisptask.appspot.com',
    iosBundleId: 'com.example.whisptask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:402878727922:ios:abcdefghijklmnop',
    messagingSenderId: '402878727922',
    projectId: 'whisptask',
    storageBucket: 'whisptask.appspot.com',
    iosBundleId: 'com.example.whisptask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ',
    appId: '1:402878727922:web:abcdefghijklmnop',
    messagingSenderId: '402878727922',
    projectId: 'whisptask',
    authDomain: 'whisptask.firebaseapp.com',
    storageBucket: 'whisptask.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
